version: 0.2
phases:
  build:
    commands:
      - docker login --username raviboda --password $dockerpassword
      - docker build -t builtimage .
      - aws ecr get-login-password | docker login --username AWS --password-stdin $ECR_ENDPOINT
      - docker tag builtimage:latest $ECR_IMAGE_URL:latest
      - docker push $ECR_IMAGE_URL:latest
artifacts:
  files:
    - '**/*'
